databases:
  - name: bpbadi-db
    plan: free
    databaseName: bpbadi
    user: bpbadi

services:
  - type: web
    name: bp-badminton
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bpbadi-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: APP_PASSWORD
        sync: false
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.11.0
